# @package _global_

defaults:
  - _self_
  - data: troposphere  
  - model: troposphere_module_fcn  
  - callbacks: default 
  - logger: wandb  
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["eval"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null

seed: 12345  # for reproducibility