"""
ShapeNet for Neural Implicit Flow.

Computes final outputs using dynamically generated weights from WeightsEmbeddingLayer.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import List, Tuple


class ShapeNet(nn.Module):
    """Shape network with dynamic per-sample weights.
    
    Takes spatial coordinates (longitude, latitude) and produces atmospheric
    variables (u, v, w, z) using weights generated by the WeightsEmbeddingLayer.
    
    Args:
        input_dim: Dimension of spatial input (typically 2: longitude, latitude)
        output_dim: Dimension of output (typically 4: u, v, w, z)
        hidden_dim: Width of hidden layers
        nlayers: Number of hidden layers
        net_type: Network type ('mlp' or 'siren')
        activation: Activation function for MLP ('relu', 'gelu', etc.)
        omega_0: Frequency parameter for SIREN
    """
    
    def __init__(
        self,
        input_dim: int,
        output_dim: int,
        hidden_dim: int,
        nlayers: int,
        net_type: str = 'mlp',
        activation: str = 'tanh',
        omega_0: float = 30.0
    ):
        super().__init__()
        
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.hidden_dim = hidden_dim
        self.nlayers = nlayers
        self.net_type = net_type
        self.activation = activation
        self.omega_0 = omega_0
        
        # Store layer dimensions for verification
        self.layer_dims = [input_dim] + [hidden_dim] * (nlayers + 1) + [output_dim]
    
    def forward(self, x, layer_params):
        """Forward pass with dynamic weights.
        
        Args:
            x: Spatial input tensor [batch_size, input_dim] containing [longitude, latitude]
            layer_params: List of (weights, biases) tuples from WeightsEmbeddingLayer
                - weights: [batch_size, fan_out, fan_in]
                - biases: [batch_size, fan_out]
        
        Returns:
            Output tensor [batch_size, output_dim] containing [u, v, w, z]
        """
        batch_size = x.shape[0]
        
        # Process each layer with dynamic weights
        h = x
        for i, (weights, biases) in enumerate(layer_params):
            # Apply linear transformation with batch-specific weights
            # h: [batch_size, fan_in]
            # weights: [batch_size, fan_out, fan_in]
            # biases: [batch_size, fan_out]
            
            h = torch.bmm(h.unsqueeze(1), weights.transpose(1, 2)).squeeze(1)
            h = h + biases
            
            # Apply activation (skip on last layer)
            if i < len(layer_params) - 1:
                if self.net_type == 'siren':
                    h = torch.sin(self.omega_0 * h)
                elif self.net_type == 'mlp':
                    h = self._apply_activation(h)
        
        return h
    
    def _apply_activation(self, x):
        """Apply MLP activation function."""
        if self.activation == 'relu':
            return F.relu(x)
        elif self.activation == 'gelu':
            return F.gelu(x)
        elif self.activation == 'tanh':
            return torch.tanh(x)
        elif self.activation == 'elu':
            return F.elu(x)
        elif self.activation == 'leaky_relu':
            return F.leaky_relu(x)
        else:
            raise ValueError(f"Unsupported activation: {self.activation}")